"use client";

import Link from "next/link";
import { useMemo, useState } from "react";

type Resource = { name: string; scope: string; description: string; phone?: string; website?: string; address?: string };
type Category = { title: string; resources: Resource[] };

const categories: Category[] = [
  { title: "Benefits & Claims Assistance", resources: [
    { name: "KDVA Benefits Representative for Laurel County — Joseph Trinetto", scope: "Kentucky / Local", description: "Free accredited veterans benefits assistance serving Laurel and nearby counties.", phone: "606-344-1003", website: "https://veterans.ky.gov/Benefits/Pages/Your-Benefits-Representative.aspx" },
    { name: "KDVA London Regional Office", scope: "Kentucky / Local", description: "Free claims, eligibility, and application assistance serving Bell, Clay, Knox, Laurel, Owsley, and Whitley counties.", phone: "502-564-9203", website: "https://veterans.ky.gov/Benefits/Pages/Your-Benefits-Representative.aspx" },
    { name: "U.S. Department of Veterans Affairs — Main Benefits Line", scope: "Federal", description: "Primary federal contact for disability compensation, pension, education, home loans, insurance, burial, and other VA benefits.", phone: "1-800-827-1000", website: "https://www.va.gov" },
    { name: "GI Bill Hotline", scope: "Federal", description: "Help with VA education benefits and GI Bill questions.", phone: "1-888-442-4551", website: "https://benefits.va.gov/gibill/contact_us.asp" },
    { name: "VA Veteran Readiness & Employment", scope: "Federal", description: "Career counseling, training, and employment assistance for eligible veterans with service-connected disabilities.", phone: "1-800-827-1000", website: "https://www.va.gov/careers-employment/vocational-rehabilitation/" },
    { name: "American Legion Post 16 — London", scope: "VSO / Local", description: "Local American Legion post supporting Laurel County veterans with community programs and benefits connections.", phone: "606-864-2627", website: "https://americanlegionpost16.org", address: "1785 Barbourville St, London, KY 40741" },
    { name: "Disabled American Veterans Chapter 66", scope: "VSO / Local", description: "London-area DAV chapter supporting disabled veterans.", phone: "606-877-1308", website: "https://davwebsites.dav.org/ky/66/SystemPages/Home.aspx" },
    { name: "Laurel County VFW Post 3302", scope: "VSO / Local", description: "Local Veterans of Foreign Wars post serving London and Laurel County.", phone: "606-389-5229", website: "https://vfwky.org/di/vfw/v2/postroster.asp", address: "3027 West Laurel Rd, London, KY" },
  ]},
  { title: "Burial & Cemetery Benefits", resources: [
    { name: "VA Burial and Memorial Benefits", scope: "Federal", description: "Information about burial in a national cemetery, memorial items, pre-need eligibility, and possible funeral-expense allowances.", phone: "1-800-827-1000", website: "https://www.va.gov/burials-memorials/" },
    { name: "National Cemetery Scheduling Office", scope: "Federal", description: "Schedule an eligible burial at a VA national cemetery.", phone: "1-800-535-1117", website: "https://www.cem.va.gov" },
    { name: "Camp Nelson National Cemetery", scope: "Federal / Kentucky", description: "National cemetery serving Kentucky veterans and eligible family members.", phone: "1-800-535-1117", website: "https://www.cem.va.gov/cems/nchp/CampNelson.asp", address: "6980 Danville Rd, Nicholasville, KY 40356" },
    { name: "Kentucky Veterans Cemetery — Southeast", scope: "Kentucky", description: "The closest Kentucky state veterans cemetery to London and Laurel County.", phone: "606-672-2750", website: "https://veterans.ky.gov/cemeteries", address: "1280 Kentucky Highway 118, Hyden, KY 41749" },
  ]},
  { title: "Crisis, Mental Health & Immediate Support", resources: [
    { name: "Veterans Crisis Line", scope: "Federal / 24-7", description: "Confidential crisis support for veterans, service members, National Guard and Reserve members, and their loved ones.", phone: "988, then press 1", website: "https://www.veteranscrisisline.net" },
    { name: "National Call Center for Homeless Veterans", scope: "Federal / 24-7", description: "Connects veterans who are homeless or at risk of homelessness with VA services.", phone: "1-877-424-3838", website: "https://www.va.gov/homeless/nationalcallcenter.asp" },
    { name: "VA Women Veterans Call Center", scope: "Federal", description: "Dedicated assistance for women veterans with questions about VA care, benefits, and services.", phone: "1-855-829-6636", website: "https://www.va.gov/womenvet/" },
  ]},
  { title: "Housing & Emergency Assistance", resources: [
    { name: "KCEOC Community Action Partnership", scope: "Local / Regional", description: "Rental and utility assistance, homelessness prevention, rapid rehousing, weatherization, and LIHEAP across the Cumberland Valley region.", phone: "606-546-3152", website: "https://www.kceoc.org", address: "5448 North US Hwy 25E, Suite A, Gray, KY 40734" },
    { name: "Kentucky River Foothills — Supportive Services for Veteran Families", scope: "Local / Regional", description: "Housing-stability assistance serving Laurel County, including deposits, eviction prevention, emergency rental help, and case management.", phone: "859-408-7017", website: "https://www.foothillscap.org" },
    { name: "Laurel County Judge-Executive’s Office", scope: "Local", description: "County government referrals for emergency assistance and community services available to Laurel County residents, including veterans.", phone: "606-864-5158", website: "https://www.laurelcounty.org", address: "203 S Main St, London, KY 40741" },
  ]},
  { title: "Records, Identification & Proof of Service", resources: [
    { name: "DD-214 and Military Records Request — National Archives", scope: "Federal", description: "Request discharge papers and other military service records needed for many benefits applications.", phone: "1-314-801-0800", website: "https://www.archives.gov/veterans/military-service-records", address: "National Personnel Records Center, 1 Archives Dr, St. Louis, MO 63138" },
    { name: "VA Veteran ID Card", scope: "Federal", description: "Apply for a VA-issued Veteran ID Card that may be accepted as proof of service for participating discounts.", phone: "1-800-827-1000", website: "https://www.va.gov/records/get-veteran-id-cards/vic/" },
    { name: "Kentucky Veteran Designation on Driver’s License", scope: "Kentucky", description: "Add a veteran designation to an eligible Kentucky driver’s license or ID card.", phone: "502-564-1257", website: "https://drive.ky.gov" },
  ]},
];

export default function VeteranResourcesPage() {
  const [query,setQuery]=useState(""); const [scope,setScope]=useState("All"); const scopes=["All","Federal","Kentucky","Local","VSO"];
  const filtered=useMemo(()=>categories.map(c=>({...c,resources:c.resources.filter(r=>{const q=query.toLowerCase().trim();return(!q||`${r.name} ${r.scope} ${r.description} ${r.phone??""} ${r.address??""}`.toLowerCase().includes(q))&&(scope==="All"||r.scope.toLowerCase().includes(scope.toLowerCase()))})})).filter(c=>c.resources.length),[query,scope]);
  const count=filtered.reduce((t,c)=>t+c.resources.length,0);
  return <main className="directory-page">
    <section className="hero"><img src="/IMG_1844.jpeg" alt="The Front Porch" className="brand-logo"/><div className="utility-links"><Link href="/">Home</Link><a href="tel:988">Call 988, then press 1</a></div><h1>Veteran Resources Directory</h1><p>Local, Kentucky, and federal resources for veterans in London, Laurel County, and the surrounding region.</p><Link href="/veteran-discounts" className="discounts-link">Veteran Benefits &amp; Discounts →</Link></section>
    <div className="crisis-wrap"><a className="crisis-card" href="tel:988"><span className="crisis-icon">★</span><span><strong>Veterans Crisis Line</strong><small>Dial 988, then press 1</small></span></a></div>
    <section className="directory" aria-label="Veteran resources directory"><div className="progress-note"><strong>Resource restoration is underway.</strong> The original compiled directory remains preserved and is being returned to this searchable layout.</div><div className="toolbar"><input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search housing, GI Bill, mental health, VFW, phone number..." aria-label="Search veteran resources"/><div className="filters">{scopes.map(i=><button key={i} className={scope===i?"active":""} onClick={()=>setScope(i)}>{i}</button>)}</div><p className="status">Showing {count} resources</p></div>
    {filtered.map(c=><section className="category" key={c.title}><h2>{c.title}</h2><div className="resource-grid">{c.resources.map(r=><article className="resource-card" key={r.name}><span className="scope">{r.scope}</span><h3>{r.name}</h3><p>{r.description}</p>{r.address&&<p className="meta"><strong>Address:</strong> {r.address}</p>}<div className="actions">{r.phone&&<a href={`tel:${r.phone.replace(/[^0-9]/g,"")}`}>Call {r.phone}</a>}{r.website&&<a href={r.website} target="_blank" rel="noreferrer">Official website</a>}</div></article>)}</div></section>)}</section>
    <style jsx>{`.directory-page{min-height:100vh;background:#f3f5f7;color:#17212b}.hero{padding:20px 18px 46px;text-align:center;background:linear-gradient(145deg,#0f2e4c,#174f79);color:#fff}.brand-logo{width:min(330px,76vw);height:auto;margin:0 auto 10px;border-radius:10px}.utility-links{max-width:1100px;margin:0 auto 20px;display:flex;justify-content:space-between}.utility-links a{color:#fff;font-weight:700}.hero h1{margin:0 0 8px;font-size:clamp(2rem,6vw,3.8rem)}.hero p{max-width:760px;margin:0 auto 20px;color:#d9e6ef}.discounts-link{display:inline-flex;padding:13px 20px;border-radius:999px;background:#b52331;color:#fff;text-decoration:none;font-weight:900}.crisis-wrap{display:flex;justify-content:flex-end;max-width:1120px;margin:12px auto 0;padding:0 16px}.crisis-card{display:flex;align-items:center;gap:10px;padding:10px 14px;border:1px solid #cbd8e6;border-radius:12px;background:#fff;color:#25364b;text-decoration:none;box-shadow:0 6px 18px rgba(7,26,51,.1)}.crisis-card strong,.crisis-card small{display:block}.crisis-card small{color:#c72828;font-weight:800}.crisis-icon{display:grid;place-items:center;width:42px;height:42px;border-radius:8px;background:#075391;color:#fff}.directory{max-width:1120px;margin:auto;padding:22px 16px 70px}.progress-note{padding:16px 18px;border:1px solid #d7c16b;border-radius:12px;background:#fff8d9}.toolbar{margin:18px 0 28px;padding:14px;border:1px solid #d6dee6;border-radius:16px;background:#fff}.toolbar input{width:100%;padding:14px 16px;border:1px solid #cbd5df;border-radius:11px;font-size:16px}.filters{display:flex;flex-wrap:wrap;gap:8px;margin-top:10px}.filters button{padding:9px 14px;border:1px solid #cbd5df;border-radius:999px;background:#fff}.filters button.active{background:#164d78;color:#fff}.category{margin-top:34px}.category h2{padding:12px 16px;border-left:6px solid #b52331;border-radius:8px;background:#123b5f;color:#fff}.resource-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:14px}.resource-card{padding:18px;border:1px solid #d8e0e7;border-radius:14px;background:#fff}.scope{display:inline-block;padding:5px 9px;border-radius:999px;background:#e6f0f8;color:#164d78;font-size:.76rem;font-weight:800}.actions{display:flex;flex-wrap:wrap;gap:8px;margin-top:14px}.actions a{padding:9px 11px;border:1px solid #c9d5df;border-radius:9px;color:#164d78;text-decoration:none;font-weight:800}@media(max-width:600px){.resource-grid{grid-template-columns:1fr}.crisis-card{width:100%}}`}</style>
  </main>;
}
